version: '3.8'

services:
  symfony:
    image: blizerto/symfony_custom_projet
    container_name: symfony_custom_projet
    volumes:
      - ./symfony:/var/www/html
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-secret}@postgres:5432/${POSTGRES_DB:-symfonydb}?serverVersion=${POSTGRES_VERSION:-13}
    networks:
      - network_postgres_symfony_adminer

  adminer:
    image: blizerto/adminer_custom_projet
    container_name: adminer_custom_projet
    ports:
      - "8040:8040"
    networks:
      - network_postgres_symfony_adminer

networks:
  network_postgres_symfony_adminer:
    name: projet_docker_esgi_network_postgres_symfony_adminer
    external: true
